- name: Copier le fichier .env sur le serveur
  copy:
    src: "/home/enzo/cpe-ecalleya-devops/ansible/.env"
    dest: "/home/admin/.env"
    mode: "0644"

- name: Vérifier si le réseau Docker existe
  docker_network:
    name: amour
  ignore_errors: yes # Évite une erreur si le réseau existe déjà

# Lancer le frontend
- name: Run the frontend container
  docker_container:
    name: proxy
    env_file: "/home/admin/.env"
    image: "enzouz12/tp-devops-proxy:latest"
    pull: true
    ports:
      - "80:80"
      - "8080:8080"
    networks:
      - name: amour
    state: started
