# FROM eclipse-temurin:21-jdk-alpine
# COPY Main.java /usr/src/
# WORKDIR /usr/src/
# RUN javac Main.java
# # TODO : in next steps (not now)

# FROM eclipse-temurin:21-jre-alpine
# # Copy resource from previous stage
# COPY --from=0 /usr/src/Main.class .
# CMD ["java", "Main"]

# Run java code with the JRE
# TODO : in next steps (not now)

# Build
FROM maven:3.9.9-amazoncorretto-21 AS my-spring-build
ENV MY_SPRING_HOME=/opt/my-spring-app 
WORKDIR $MY_SPRING_HOME
COPY pom.xml .
COPY src ./src
RUN mvn package -DskipTests dependency:go-offline

# Run
FROM amazoncorretto:21
ENV MY_SPRING_HOME=/opt/my-spring-app 
WORKDIR $MY_SPRING_HOME
COPY --from=my-spring-build $MY_SPRING_HOME/target/*.jar $MY_SPRING_HOME/spring-app.jar

ENTRYPOINT ["java", "-jar", "spring-app.jar"]

EXPOSE 8080