- name: Copy .env file to the server
  copy:
    src: "/home/enzo/cpe-ecalleya-devops/ansible/.env"
    dest: "/home/admin/.env"
    mode: "0644"

- name: Run the database container
  docker_container:
    name: database
    env_file: "/home/admin/.env"
    image: "enzouz12/tp-devops-database:latest"
    pull: true
    networks:
      - name: amour
    volumes:
      - pgdata:/var/lib/postgresql/data
    state: started
